image: archlinux/base:latest

stages:
  - build-release
  - clean

.build_and_release: &buildandrelease
  before_script:
    - pacman-key --init && \
      pacman-key --populate archlinux || true
    - pacman -Syu --noconfirm archiso patch grep gettext file xz tar git
    - curl -L https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 | tar -jx --strip-components 3 -C /usr/local/bin bin/linux/amd64/github-release
    - cp groovy-ux-repo.conf /etc/pacman.d
    - grep -q groovy-ux-repo.conf /etc/pacman.conf || echo -e "\nInclude = /etc/pacman.d/groovy-ux-repo.conf" >> /etc/pacman.conf
    - ln -s "$(pwd)" /work && ls -l /work
    - for i in $(seq 0 9) ; do [[ ! -b /dev/loop$i ]] && mknod /dev/loop$i -m0660 b 7 $i ; done
    - ./build.sh
    - xz -T 0 /work/output/"groovyarcade-$(date +%Y.%m)-x86_64.iso"

build_iso_testing:
  stage: build-release
  only:
    - branches
  except:
    - master
  <<: *buildandrelease
  script:
    - ./release.sh -dci
  environment:
    name: testing/$CI_COMMIT_REF_SLUG
    url: https://github.com/substring/os/releases/tag/$CI_COMMIT_REF_SLUG
    on_stop: clean_release
    
build_iso:
  stage: build-release
  only:
    - master
    - tags
  <<: *buildandrelease
  script:
    - ./release.sh -dcip
    
clean_release:
  image: alpine
  stage: clean
  when: manual
  dependencies: []
  only:
    - branches
  before_script:
    - echo "Deleting deployment $CI_COMMIT_REF_SLUG"
  environment:
    name: testing/$CI_COMMIT_REF_SLUG
    action: stop
  script:
    - apk add curl
    - curl -L https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 | tar -jx --strip-components 3 -C /usr/local/bin bin/linux/amd64/github-release
    - github-release delete -t "$CI_COMMIT_REF_SLUG"
